# -*- coding: utf-8 -*-
"""problem1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iyUfIIFzf9ntFxp5WkU7zyGS0BiM1z0l

By using a tail pointer, it allows a new node to be added to the end of a linked list without going through the entire list
"""